
### Create a product
POST http://192.168.0.19:5000/api/v1/products/new
Content-Type: application/json
Accept: application/json

{
    "title": "kqhubafrica.com",
    "expires": "2021,7,7",
    "price": "140000",
    "customer": {
        "first_name": "Wabwire",
        "gender": "Male",
        "phone": "+256775101122",
        "email": "wabwire@kqhubafrica.com"
    }
}

### Retrieve Products
GET http://192.168.0.19:5000/api/v1/products

### Get a Product
GET http://192.168.0.19:5000/api/v1/products/60ad26d677a801fc8586ffbe

### Update a Product
PUT http://192.168.0.19:5000/api/v1/products/edit
Content-Type: application/json

{
    "id":"60a2ccb8ee3408b0c82084dd",
    "info": {
        "customer": {
            "first_name": "Jimmy",
            "last_name": "Ssenabulya",
            "gender": "Male",
            "phone":"256704255404",
            "email":"jimmy.ssenabulya@gmail.com"
        },
        "title":"jamesssenfuma.com"
    }
}

### Delete a Product

DELETE http://192.168.0.19:5000/api/v1/products/delete
Content-Type: application/json

{
    "id": "60a295dfd1ac039b674ed56c"
}

### Add a new Member
POST http://192.168.0.11:5000/api/v1/members/new
Content-Type: application/json

{
    "username": "wampamba",
    "password": "123456",
    "email": "davidwampamba@gmail.com",
    "first_name": "David",
    "last_name": "Wampamba",
    "phone": 256704255401
}

### Get Members

GET http://192.168.0.11:5000/api/v1/members

### Login
POST http://192.168.0.11:5000/api/v1/members/login
Content-Type: application/json

{
    "username":"David",
    "password":"Password"
}

### Update member
PUT http://192.168.0.11:5000/api/v1/members
Content-Type: application/json

{

}

### Delete a member

DELETE http://192.168.0.11:5000/members
Content-Type: application/json

{
    "id": "60a295dfd1ac039b674ed56c"
}